server:
      port: 9001
      session-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8
      context-path: /shiro

spring:

    datasource:
      url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    freemarker:
      cache: false
      template-loader-path: classpath:/templates
    #前缀
      suffix: .htm
    #后缀
      prefix: /htm/
    jpa:
      database: mysql
      show-sql: false

    profiles:
      active: local #product
    output:
      ansi:
        enabled: DETECT
#日志
logging:
  config: classpath:logback-spring.xml

mybatis:
 type-aliases-package: com.springboot.entity
 mapper-locations: classpath:mapper/*Mapper.xml
 map-underscore-to-camel-case: true
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

